services:
  postgresdbserver:
    image: postgres:9.6.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=sysml2
    ports:
      - "5432:5432"
    volumes:
      - postgresdbvol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - thenetwork
  sysmlapiserver:
    image: mbse-mashup-local-sysmlv2api
    tty: false
    environment:
      - JDBC_USER=postgres
      - JDBC_PASSWORD=mysecretpassword
      - JDBC_URL=jdbc:postgresql://postgresdbserver:5432/sysml2
      - HIBERNATE_SHOW_SQL=false
      - HIBERNATE_HBM2DDL=update
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      postgresdbserver:
        condition: service_healthy
    networks:
      - thenetwork
networks:
  thenetwork:
    labels:
      com.docker.compose.network: thenetwork
volumes:
  postgresdbvol:
    driver: local
