FROM sbtscala/scala-sbt:TAGTOBEDEFINED

# found Dockerfile at https://github.com/Systems-Modeling/SysML-v2-API-Services/issues/115
# according to docker hub docu of sbtscala/scala-sbt the images are tagged according to
# versions like: <JDK version>_<sbt version>_<Scala version>

RUN java --version
RUN sbt --version
RUN scala -version

RUN echo "SUCCESS_ToolsAvailable TAG: TAGTOBEDEFINED"

WORKDIR /app
COPY ./ /app

RUN java --version
RUN sbt --version
RUN scala -version

RUN echo "SUCCESS_AppSourcesCopied TAG: TAGTOBEDEFINED"

# Warm up sbt and download dependencies
RUN sbt update

RUN java --version
RUN sbt --version
RUN scala -version

RUN echo "SUCCESS_SBTupdated TAG: TAGTOBEDEFINED"

RUN sbt -v clean compile

RUN echo "SUCCESS_ApplicationCompiled TAG: TAGTOBEDEFINED"

# Create distribution
RUN sbt dist

RUN echo "SUCCESS_DistBuilt TAG: TAGTOBEDEFINED"

# RUN sbt -v evicted
EXPOSE  9000
CMD ["sbt", "-v", "run"]
