services:
  postgresdbserver:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=sysml2
    ports:
      - "5432:5432"
    volumes:
      - postgresdbvol:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - thenetwork
  sysmlapiserver:
    # image: mbse-mashup-local-sysmlv2api
    image: mbsemashup/sysmlv2-api.pilotimpl:latest
    platform: linux/amd64
    tty: false
    environment:
      - HIBERNATE_SHOW_SQL=false
      # - HIBERNATE_HBM2DDL=none
      - HIBERNATE_HBM2DDL=update
      # - HIBERNATE_HBM2DDL=create-drop
      # ------- POSTGRES ------
      - JDBC_DRIVER=org.postgresql.Driver
      - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - JDBC_URL=jdbc:postgresql://postgresdbserver:5432/sysml2
      - JDBC_USER=postgres
      - JDBC_PASSWORD=mysecretpassword
      # - ALLOWED_HOSTS=0.0.0.0:9000
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      postgresdbserver:
        condition: service_healthy
    networks:
      - thenetwork
networks:
  thenetwork:
    labels:
      com.docker.compose.network: thenetwork
volumes:
  postgresdbvol:
    driver: local
