endpoints:
- name: sysml-api-server
  url: "http://sysmlapiserver:9000"
  interval: 30s
  conditions:
  - "[STATUS] == 200"
- name: postgres-db-server
  group: database
  url: tcp://postgresdbserver:5432
  interval: 30s
  conditions:
  - "[CONNECTED] == true"
